// Hand-maintained types that tygo cannot generate. Everything the
// SPA decodes from an exported Go struct in internal/adminapi lives
// in the sibling types.ts, which is generated by `make tygo` and
// checked in CI by `make tygo-check` — never hand-edit that file.
//
// What belongs here instead, and why:
//   - String-literal unions (Window / Bucket / Dimension): the Go
//     side validates these as plain strings, so there is no struct
//     for tygo to translate.
//   - ApiError: the phase-7 error envelope is built inline by
//     adminapi's writeError helper (a map, not a struct).
//   - TrustOrg / TrustStatus: mirror gateway/internal/trust, a
//     package outside tygo.yaml's adminapi scope, re-named for the
//     dashboard (trust.Org -> TrustOrg, trust.StatusResponse ->
//     TrustStatus).
//   - Chat / usage shapes (ChatMessage, TokenUsage, CacheDebug, …):
//     Bifrost pass-through fields that Go carries as
//     json.RawMessage (tygo emits `any`); typed here to the depth
//     the RunDetail drawer actually renders.
//
// Keep each block in lockstep with the Go source it names.

// ─── enums validated Go-side as strings ─────────────────────────────

// Window options the SPA exposes to the operator. Kept in lockstep
// with the Go-side validation in observability.go > parseWindow.
export type Window = "1h" | "6h" | "24h" | "7d" | "30d";

// Bucket options for the histogram endpoints — same source-of-truth
// note as Window.
export type Bucket = "1m" | "5m" | "10m" | "1h" | "6h" | "1d";

// Dimension values the histogram endpoint accepts. Phase 11 removed
// `realm-id` — every row in a swarm's logs.db is implicitly for
// that swarm's realm, and the realm is surfaced on the trust-status
// card instead of as a per-row column.
export type Dimension =
  | "agent-name"
  | "run-id"
  | "session-id"
  | "user-id";

// ─── error envelope ─────────────────────────────────────────────────

// Phase-7 error envelope (returned on 4xx/5xx). Mirrors the map
// built by internal/adminapi's writeError helper.
export interface ApiError {
  error: {
    code: string;
    message: string;
  };
}

// ─── trust registry (gateway/internal/trust) ────────────────────────

// Trust-registry Org entry — mirrors gateway/internal/trust.Org.
// Surfaced on the dashboard's Provenance card so an operator can
// see which org's signature authorized a run, plus the pubkey /
// issuer URL the plugin would verify against.
export interface TrustOrg {
  org_id: string;
  pubkey: string;
  issuer_url: string;
  revocation_poll_seconds: number;
  grace_pubkeys?: string[];
  grace_until?: string;
}

// Trust-registry status — mirrors gateway/internal/trust.StatusResponse.
// The Provenance card on RunDetail uses `realm_id` to show the
// swarm's self-identity ("this run was processed by swarm w1"),
// since phase 11 dropped the per-row realm-id metadata column.
export interface TrustStatus {
  claimed: boolean;
  org_count: number;
  orgs: string[];
  seed_source: "" | "env" | "api";
  last_modified: string;
  /** Set on multi-swarm deployments; absent / empty on single-swarm. */
  realm_id?: string;
}

// ─── Bifrost pass-through shapes (json.RawMessage on the Go side) ───

// One message in a chat-style input_history / output_message.
// Mirrors Bifrost's `schemas.ChatMessage` to the depth the drawer
// renders: role, content (string OR an array of content blocks),
// optional tool-call list (assistant) and tool_call_id (tool reply).
// Everything is optional because providers vary in which fields
// they populate, and the drawer falls back to JSON for anything it
// doesn't recognize.
export interface ChatMessage {
  role?: string;
  name?: string;
  /** OpenAI/Anthropic-style: either a plain string or an array of
   *  typed content blocks. */
  content?: string | ChatContentBlock[] | null;
  /** Tool messages: which prior tool_call this is the result for. */
  tool_call_id?: string;
  /** Assistant tool calls. */
  tool_calls?: ChatToolCall[];
  /** Anthropic / OpenAI reasoning summaries. */
  reasoning?: string;
  refusal?: string;
}

export interface ChatContentBlock {
  type: string;
  text?: string;
  refusal?: string;
  /** Anthropic-style cache marker. When present on a block the
   *  provider charged this block as a cache write (or read on a
   *  subsequent call). */
  cache_control?: { type?: string } | null;
  cachePoint?: { type?: string } | null;
  image_url?: unknown;
  input_audio?: unknown;
  file?: unknown;
}

export interface ChatToolCall {
  id?: string;
  type?: string;
  function?: { name?: string; arguments?: string };
}

/** Provider-reported usage breakdown. Source: Bifrost
 *  `schemas.BifrostLLMUsage`. The `prompt_tokens_details` sub-
 *  object is where the cache split lives — Anthropic populates
 *  `cached_write_tokens` (prompt cache writes) and
 *  `cached_read_tokens`; OpenAI uses `cached_read_tokens` only. */
export interface TokenUsage {
  prompt_tokens?: number;
  completion_tokens?: number;
  total_tokens?: number;
  prompt_tokens_details?: {
    text_tokens?: number;
    audio_tokens?: number;
    image_tokens?: number;
    cached_read_tokens?: number;
    cached_write_tokens?: number;
    cached_write_token_details?: {
      cached_write_tokens_5m?: number;
      cached_write_tokens_1h?: number;
    };
  };
  completion_tokens_details?: {
    reasoning_tokens?: number;
    accepted_prediction_tokens?: number;
  };
  cost?: unknown;
}

/** Semantic cache verdict. Source: `schemas.BifrostCacheDebug`.
 *  Distinct from prompt-cache token splits (those live in
 *  TokenUsage above). Present only when a semantic cache plugin
 *  is configured. */
export interface CacheDebug {
  cache_hit: boolean;
  cache_id?: string;
  hit_type?: string;
  requested_provider?: string;
  requested_model?: string;
  provider_used?: string;
  model_used?: string;
  input_tokens?: number;
  threshold?: number;
  similarity?: number;
}
