// Code generated by tygo. DO NOT EDIT.
//
// To regenerate from the Go source of truth:
//   make tygo   (or: tygo generate from gateway/)
//
// Source: github.com/stakwork/stakgraph/gateway/internal/adminapi
//
// Phase 8 hand-maintains this file as a stop-gap until the tygo
// codegen runs in CI. The shapes below MUST stay byte-equivalent to
// the Go structs they mirror (LoginResponse, MeResponse,
// SpendByAgentResponse, SpendByUserResponse, HistogramCostResponse,
// RunDetailResponse and friends). Any drift fails the matching
// adminapi Go tests on next run.

/* eslint-disable */

export interface LoginResponse {
  user: string;
}

export interface MeResponse {
  user: string;
  iat: number;
  last_seen: number;
}

export interface AgentSpend {
  agent_name: string;
  total_cost: number;
  total_tokens: number;
  request_count: number;
}

export interface SpendByAgentResponse {
  window: string;
  results: AgentSpend[];
}

export interface UserSpend {
  user_id: string;
  user_name: string;
  total_cost: number;
  total_tokens: number;
  request_count: number;
}

export interface SpendByUserResponse {
  window: string;
  results: UserSpend[];
}

export interface HistogramPoint {
  ts: string;
  cost: number;
}

export interface HistogramSeries {
  dimension_value: string;
  points: HistogramPoint[];
}

export interface HistogramCostResponse {
  bucket_size_seconds: number;
  dimension: string;
  series: HistogramSeries[];
}

export interface RunLogEntry {
  id: string;
  timestamp: string;
  provider: string;
  model: string;
  status: string;
  cost: number;
  latency: number;
  metadata: Record<string, string>;
}

export interface RunStats {
  total_requests: number;
  total_cost: number;
  total_tokens: number;
}

export interface RunDetailResponse {
  run_id: string;
  logs: RunLogEntry[];
  stats: RunStats;
}

// Phase-7 error envelope (returned on 4xx/5xx).
export interface ApiError {
  error: {
    code: string;
    message: string;
  };
}

// Window options the SPA exposes to the operator. Kept in lockstep
// with the Go-side validation in observability.go > parseWindow.
export type Window = "1h" | "6h" | "24h" | "7d" | "30d";

// Bucket options for the histogram endpoints — same source-of-truth
// note as Window.
export type Bucket = "1m" | "5m" | "10m" | "1h" | "6h" | "1d";

// Dimension values the histogram endpoint accepts.
export type Dimension =
  | "agent-name"
  | "run-id"
  | "session-id"
  | "realm-id"
  | "user-id";
