// Code generated by tygo. DO NOT EDIT.
//
// To regenerate from the Go source of truth:
//   make tygo   (or: tygo generate from gateway/)
//
// Source: github.com/stakwork/stakgraph/gateway/internal/adminapi
//
// Phase 8 hand-maintains this file as a stop-gap until the tygo
// codegen runs in CI. The shapes below MUST stay byte-equivalent to
// the Go structs they mirror (LoginResponse, MeResponse,
// SpendByAgentResponse, SpendByUserResponse, HistogramCostResponse,
// RunDetailResponse and friends). Any drift fails the matching
// adminapi Go tests on next run.

/* eslint-disable */

export interface LoginResponse {
  user: string;
}

export interface MeResponse {
  user: string;
  iat: number;
  last_seen: number;
}

export interface AgentSpend {
  agent_name: string;
  total_cost: number;
  total_tokens: number;
  request_count: number;
}

export interface SpendByAgentResponse {
  window: string;
  results: AgentSpend[];
}

export interface UserSpend {
  user_id: string;
  user_name: string;
  total_cost: number;
  total_tokens: number;
  request_count: number;
}

export interface SpendByUserResponse {
  window: string;
  results: UserSpend[];
}

export interface HistogramPoint {
  ts: string;
  cost: number;
}

export interface HistogramSeries {
  dimension_value: string;
  points: HistogramPoint[];
}

export interface HistogramCostResponse {
  bucket_size_seconds: number;
  dimension: string;
  series: HistogramSeries[];
}

export interface RunLogEntry {
  id: string;
  timestamp: string;
  provider: string;
  model: string;
  status: string;
  cost: number;
  latency: number;
  metadata: Record<string, string>;
}

export interface RunStats {
  total_requests: number;
  total_cost: number;
  total_tokens: number;
}

export interface RunDetailResponse {
  run_id: string;
  logs: RunLogEntry[];
  stats: RunStats;
}

// One row of UserDetailResponse.AgentsUsed — which agents the user
// invoked in the window, and how much each cost.
export interface UserAgentUsage {
  agent_name: string;
  total_cost: number;
  request_count: number;
  last_seen?: string;
}

// One row of UserDetailResponse.RecentRuns — links into RunDetail.
export interface UserRunSummary {
  run_id: string;
  agent_name: string;
  total_cost: number;
  request_count: number;
  first_seen?: string;
  last_seen?: string;
}

// /_plugin/users/:id response.
export interface UserDetailResponse {
  user_id: string;
  window: string;
  total_cost: number;
  request_count: number;
  agents_used: UserAgentUsage[];
  recent_runs: UserRunSummary[];
  first_seen?: string;
  last_seen?: string;
}

// Trust-registry Org entry — mirrors gateway/internal/trust.Org.
// Surfaced on the dashboard's Provenance card so an operator can
// see which org's signature authorized a run, plus the pubkey /
// issuer URL the plugin would verify against.
export interface TrustOrg {
  org_id: string;
  pubkey: string;
  issuer_url: string;
  revocation_poll_seconds: number;
  grace_pubkeys?: string[];
  grace_until?: string;
}

// Per-agent budget (phase-8.5). Cap and the derived fields can be
// null when no budget is configured for the agent — the UI renders
// "no budget" rather than "$0".
export interface AgentBudgetResponse {
  agent_name: string;
  cap_usd: number | null;
  window: string;
  period_start?: string;
  period_end?: string;
  spent_usd: number;
  remaining_usd: number | null;
  ratio: number | null;
}

// Phase-7 error envelope (returned on 4xx/5xx).
export interface ApiError {
  error: {
    code: string;
    message: string;
  };
}

// Window options the SPA exposes to the operator. Kept in lockstep
// with the Go-side validation in observability.go > parseWindow.
export type Window = "1h" | "6h" | "24h" | "7d" | "30d";

// Bucket options for the histogram endpoints — same source-of-truth
// note as Window.
export type Bucket = "1m" | "5m" | "10m" | "1h" | "6h" | "1d";

// Dimension values the histogram endpoint accepts.
export type Dimension =
  | "agent-name"
  | "run-id"
  | "session-id"
  | "realm-id"
  | "user-id";
