// Code generated by tygo. DO NOT EDIT.
//
// To regenerate from the Go source of truth:
//   make tygo   (or: tygo generate from gateway/)
//
// Source: github.com/stakwork/stakgraph/gateway/internal/adminapi
//
// Phase 8 hand-maintains this file as a stop-gap until the tygo
// codegen runs in CI. The shapes below MUST stay byte-equivalent to
// the Go structs they mirror (LoginResponse, MeResponse,
// SpendByAgentResponse, SpendByUserResponse, HistogramCostResponse,
// RunDetailResponse and friends). Any drift fails the matching
// adminapi Go tests on next run.

/* eslint-disable */

export interface LoginResponse {
  user: string;
}

export interface MeResponse {
  user: string;
  iat: number;
  last_seen: number;
}

export interface AgentSpend {
  agent_name: string;
  total_cost: number;
  total_tokens: number;
  request_count: number;
}

export interface SpendByAgentResponse {
  window: string;
  results: AgentSpend[];
}

export interface UserSpend {
  user_id: string;
  user_name: string;
  total_cost: number;
  total_tokens: number;
  request_count: number;
}

export interface SpendByUserResponse {
  window: string;
  results: UserSpend[];
}

export interface HistogramPoint {
  ts: string;
  cost: number;
}

export interface HistogramSeries {
  dimension_value: string;
  points: HistogramPoint[];
}

export interface HistogramCostResponse {
  bucket_size_seconds: number;
  dimension: string;
  series: HistogramSeries[];
}

export interface RunLogEntry {
  id: string;
  timestamp: string;
  provider: string;
  model: string;
  status: string;
  cost: number;
  latency: number;
  metadata: Record<string, string>;
}

export interface RunStats {
  total_requests: number;
  total_cost: number;
  total_tokens: number;
}

export interface RunDetailResponse {
  run_id: string;
  logs: RunLogEntry[];
  stats: RunStats;
}

// One message in a chat-style input_history / output_message.
// Mirrors Bifrost's `schemas.ChatMessage` to the depth the drawer
// renders: role, content (string OR an array of content blocks),
// optional tool-call list (assistant) and tool_call_id (tool reply).
// Everything is optional because providers vary in which fields
// they populate, and the drawer falls back to JSON for anything it
// doesn't recognize.
export interface ChatMessage {
  role?: string;
  name?: string;
  /** OpenAI/Anthropic-style: either a plain string or an array of
   *  typed content blocks. */
  content?: string | ChatContentBlock[] | null;
  /** Tool messages: which prior tool_call this is the result for. */
  tool_call_id?: string;
  /** Assistant tool calls. */
  tool_calls?: ChatToolCall[];
  /** Anthropic / OpenAI reasoning summaries. */
  reasoning?: string;
  refusal?: string;
}

export interface ChatContentBlock {
  type: string;
  text?: string;
  refusal?: string;
  /** Anthropic-style cache marker. When present on a block the
   *  provider charged this block as a cache write (or read on a
   *  subsequent call). */
  cache_control?: { type?: string } | null;
  cachePoint?: { type?: string } | null;
  image_url?: unknown;
  input_audio?: unknown;
  file?: unknown;
}

export interface ChatToolCall {
  id?: string;
  type?: string;
  function?: { name?: string; arguments?: string };
}

/** Provider-reported usage breakdown. Source: Bifrost
 *  `schemas.BifrostLLMUsage`. The `prompt_tokens_details` sub-
 *  object is where the cache split lives — Anthropic populates
 *  `cached_write_tokens` (prompt cache writes) and
 *  `cached_read_tokens`; OpenAI uses `cached_read_tokens` only. */
export interface TokenUsage {
  prompt_tokens?: number;
  completion_tokens?: number;
  total_tokens?: number;
  prompt_tokens_details?: {
    text_tokens?: number;
    audio_tokens?: number;
    image_tokens?: number;
    cached_read_tokens?: number;
    cached_write_tokens?: number;
    cached_write_token_details?: {
      cached_write_tokens_5m?: number;
      cached_write_tokens_1h?: number;
    };
  };
  completion_tokens_details?: {
    reasoning_tokens?: number;
    accepted_prediction_tokens?: number;
  };
  cost?: unknown;
}

/** Semantic cache verdict. Source: `schemas.BifrostCacheDebug`.
 *  Distinct from prompt-cache token splits (those live in
 *  TokenUsage above). Present only when a semantic cache plugin
 *  is configured. */
export interface CacheDebug {
  cache_hit: boolean;
  cache_id?: string;
  hit_type?: string;
  requested_provider?: string;
  requested_model?: string;
  provider_used?: string;
  model_used?: string;
  input_tokens?: number;
  threshold?: number;
  similarity?: number;
}

// CallDetailResponse — /_plugin/runs/:run_id/calls/:call_id.
//
// The full body of one LLM call: same fields as a list row, plus
// the heavy JSON columns Bifrost strips from /api/logs. Chat-shaped
// fields (input_history / output_message) are typed so the drawer
// can render bubble UIs; everything else stays opaque.
export interface CallDetailResponse {
  id: string;
  run_id: string;
  timestamp: string;
  provider: string;
  model: string;
  status: string;
  cost: number;
  latency: number;
  customer_id: string;
  metadata: Record<string, string>;

  stop_reason?: string;
  stream: boolean;
  number_of_retries: number;
  fallback_index: number;

  token_usage?: TokenUsage;
  cache_debug?: CacheDebug;

  input_history?: ChatMessage[];
  output_message?: ChatMessage;
  params?: unknown;
  tools?: unknown;
  error_details?: unknown;
  raw_request?: string;
  raw_response?: string;
  content_summary?: string;
}

// One row of UserDetailResponse.AgentsUsed — which agents the user
// invoked in the window, and how much each cost.
export interface UserAgentUsage {
  agent_name: string;
  total_cost: number;
  request_count: number;
  last_seen?: string;
}

// One row of UserDetailResponse.RecentRuns — links into RunDetail.
export interface UserRunSummary {
  run_id: string;
  agent_name: string;
  total_cost: number;
  request_count: number;
  first_seen?: string;
  last_seen?: string;
}

// /_plugin/users/:id response.
export interface UserDetailResponse {
  user_id: string;
  window: string;
  total_cost: number;
  request_count: number;
  agents_used: UserAgentUsage[];
  recent_runs: UserRunSummary[];
  first_seen?: string;
  last_seen?: string;
}

// Trust-registry Org entry — mirrors gateway/internal/trust.Org.
// Surfaced on the dashboard's Provenance card so an operator can
// see which org's signature authorized a run, plus the pubkey /
// issuer URL the plugin would verify against.
export interface TrustOrg {
  org_id: string;
  pubkey: string;
  issuer_url: string;
  revocation_poll_seconds: number;
  grace_pubkeys?: string[];
  grace_until?: string;
}

// Per-agent budget (phase-8.5). Cap and the derived fields can be
// null when no budget is configured for the agent — the UI renders
// "no budget" rather than "$0".
export interface AgentBudgetResponse {
  agent_name: string;
  cap_usd: number | null;
  window: string;
  period_start?: string;
  period_end?: string;
  spent_usd: number;
  remaining_usd: number | null;
  ratio: number | null;
}

// Phase-7 error envelope (returned on 4xx/5xx).
export interface ApiError {
  error: {
    code: string;
    message: string;
  };
}

// Window options the SPA exposes to the operator. Kept in lockstep
// with the Go-side validation in observability.go > parseWindow.
export type Window = "1h" | "6h" | "24h" | "7d" | "30d";

// Bucket options for the histogram endpoints — same source-of-truth
// note as Window.
export type Bucket = "1m" | "5m" | "10m" | "1h" | "6h" | "1d";

// Dimension values the histogram endpoint accepts.
export type Dimension =
  | "agent-name"
  | "run-id"
  | "session-id"
  | "realm-id"
  | "user-id";
