package macaroon_test

// Pure-Go tests for the UserAuthorization.Budget field added in
// phase 4 (see gateway/plans/phases/phase-4-macaroon-shape.md
// "Budget envelope"). These are NOT fixture-driven: cross-language
// byte-equivalence fixtures live in gateway/auth/fixtures/*.json and
// are regenerated by the TS sibling. Adding a Go-only fixture here
// would break that symmetry. When the TS side grows budget support,
// fixtures 05+ will be added by `regenerate-fixtures.ts` and picked
// up automatically by fixtures_test.go.
//
// What we test here is purely the verifier's new code path:
//
//   1. Absent Budget verifies as before (byte-compat with v=1 wire).
//   2. Budget present + Invocation within MaxPerInvocationUSD: ok.
//   3. Budget present + Invocation exceeds MaxPerInvocationUSD:
//      rejected with ErrUAPerInvocationExceeded at signature time.
//   4. MaxPerInvocationUSD == 0 disables the per-invocation cap even
//      when Budget is otherwise populated.
//   5. Claims surfaces UANonce and UABudget for the adapter's
//      cumulative-cap pipeline (phase 6 cost:ua:<nonce>).

import (
	"testing"
	"time"

	macaroon "github.com/stakwork/stakgraph/gateway/auth/go"
)

// Deterministic test keys. Same scalars used in trust/registry_test.go;
// keeping them in lock-step makes it easy to script multi-package
// scenarios later.
var (
	budgetOrgPriv  = mustHex32("aa11" + repeat("0", 60))
	budgetUserPriv = mustHex32("bb22" + repeat("0", 60))
)

// repeat is a tiny helper so the const initialisers above stay readable.
// Same as strings.Repeat but inlinable at package init.
func repeat(s string, n int) string {
	out := ""
	for i := 0; i < n; i++ {
		out += s
	}
	return out
}

// mustHex32 decodes a 64-char hex string into 32 bytes, panicking on
// shape mismatch. Used only at package init for fixed test keys.
func mustHex32(s string) []byte {
	if len(s) != 64 {
		panic("budget_test: hex key must be 64 chars (32 bytes), got " + s)
	}
	b, err := macaroon.HexToBytes(s)
	if err != nil {
		panic("budget_test: " + err.Error())
	}
	return b
}

// buildVerifiableMacaroon wires together a fully-signed macaroon
// using the package's own signer helpers, so we exercise the
// production sign+verify round-trip rather than hand-rolled JSON.
//
// The caller supplies the Budget pointer (nil for no budget) and the
// invocation's max_cost_usd. Everything else is fixed and minimal:
// one realm, one agent, no attenuations. Times are wall-clock so
// "now" passed to Verify can be the same time.Now we used to set
// iat/exp.
func buildVerifiableMacaroon(t *testing.T, budget *macaroon.Budget, invMaxCostUSD float64) (string, macaroon.Policy, time.Time) {
	t.Helper()

	orgPub, err := macaroon.EcdsaSecp256k1PublicKey(budgetOrgPriv)
	if err != nil {
		t.Fatalf("derive org pubkey: %v", err)
	}
	userPub, err := macaroon.Ed25519PublicKey(budgetUserPriv)
	if err != nil {
		t.Fatalf("derive user pubkey: %v", err)
	}

	now := time.Now().UTC().Truncate(time.Second)
	iat := now.Add(-1 * time.Second).Format(time.RFC3339)
	uaExp := now.Add(24 * time.Hour).Format(time.RFC3339)
	invExp := now.Add(10 * time.Minute).Format(time.RFC3339)

	ua := macaroon.UserAuthorization{
		UserID:     "u_alice",
		UserPubkey: macaroon.PubKey{Alg: macaroon.AlgEd25519, Key: macaroon.BytesToHex(userPub)},
		Agents:     []string{"coder"},
		Budget:     budget,
		IAT:        iat,
		Exp:        uaExp,
		// 32 hex chars (128-bit nonce) — fixed because nothing in
		// these tests cares about uniqueness.
		Nonce: "9f4e000000000000000000000000abcd",
	}
	signedUA, err := macaroon.SignUserAuthorizationSingle(ua, budgetOrgPriv)
	if err != nil {
		t.Fatalf("sign ua: %v", err)
	}

	inv := macaroon.Invocation{
		Agents:     []string{"coder"},
		RunID:      "r_budget_test",
		MaxCostUSD: invMaxCostUSD,
		MaxSteps:   100,
		IAT:        iat,
		Exp:        invExp,
		Nonce:      "7c2a000000000000000000000000abcd",
	}
	signedInv, err := macaroon.SignInvocation(inv, budgetUserPriv)
	if err != nil {
		t.Fatalf("sign invocation: %v", err)
	}

	m := macaroon.Macaroon{
		V:                 1,
		OrgID:             "org_budget_test",
		UserAuthorization: signedUA,
		Invocation:        signedInv,
		Attenuations:      nil,
	}
	encoded, err := macaroon.EncodeMacaroon(m)
	if err != nil {
		t.Fatalf("encode macaroon: %v", err)
	}

	policy := macaroon.Policy{
		Type: macaroon.PolicySingle,
		Key:  &macaroon.PubKey{Alg: macaroon.AlgEcdsaSecp256k1Sha256, Key: macaroon.BytesToHex(orgPub)},
	}

	return encoded, policy, now
}

func TestBudget_Absent_VerifiesAsBefore(t *testing.T) {
	encoded, policy, now := buildVerifiableMacaroon(t, nil, 5.00)
	claims, err := macaroon.Verify(encoded, policy, now)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}
	if claims.UABudget != nil {
		t.Fatalf("expected UABudget nil, got %+v", claims.UABudget)
	}
	if claims.UANonce == "" {
		t.Fatal("expected UANonce to be surfaced even when budget is absent")
	}
}

func TestBudget_WithinPerInvocationCap_Verifies(t *testing.T) {
	budget := &macaroon.Budget{
		MaxTotalUSD:         1000,
		MaxPerInvocationUSD: 25,
	}
	encoded, policy, now := buildVerifiableMacaroon(t, budget, 5.00)
	claims, err := macaroon.Verify(encoded, policy, now)
	if err != nil {
		t.Fatalf("verify within-cap should succeed: %v", err)
	}
	if claims.UABudget == nil {
		t.Fatal("expected UABudget on claims")
	}
	if claims.UABudget.MaxTotalUSD != 1000 || claims.UABudget.MaxPerInvocationUSD != 25 {
		t.Fatalf("budget round-trip mismatch: %+v", claims.UABudget)
	}
	if claims.UANonce != "9f4e000000000000000000000000abcd" {
		t.Fatalf("UANonce mismatch: %s", claims.UANonce)
	}
}

func TestBudget_ExceedsPerInvocationCap_Rejected(t *testing.T) {
	budget := &macaroon.Budget{
		MaxTotalUSD:         1000,
		MaxPerInvocationUSD: 25,
	}
	// Invocation asks for 50; cap is 25 — must reject.
	encoded, policy, now := buildVerifiableMacaroon(t, budget, 50.00)
	_, err := macaroon.Verify(encoded, policy, now)
	if err == nil {
		t.Fatal("verify should have rejected over-cap invocation")
	}
	ve, ok := err.(*macaroon.VerifyError)
	if !ok {
		t.Fatalf("expected *VerifyError, got %T: %v", err, err)
	}
	if ve.Code != macaroon.ErrUAPerInvocationExceeded {
		t.Fatalf("wrong error code: got %s want %s", ve.Code, macaroon.ErrUAPerInvocationExceeded)
	}
}

func TestBudget_ZeroPerInvocationDisablesCap(t *testing.T) {
	// MaxPerInvocationUSD=0 means "no per-call cap" (only the
	// cumulative MaxTotalUSD applies, and that's adapter-enforced).
	// An invocation with a large MaxCostUSD must still verify.
	budget := &macaroon.Budget{
		MaxTotalUSD:         1000,
		MaxPerInvocationUSD: 0, // explicit "no cap"
	}
	encoded, policy, now := buildVerifiableMacaroon(t, budget, 999.99)
	if _, err := macaroon.Verify(encoded, policy, now); err != nil {
		t.Fatalf("zero per-invocation cap should allow any size: %v", err)
	}
}

func TestBudget_ExactlyAtCap_Verifies(t *testing.T) {
	// Boundary: invocation == cap should be allowed. Only strictly
	// greater is rejected (matches the > comparison in verify.go).
	budget := &macaroon.Budget{MaxPerInvocationUSD: 25}
	encoded, policy, now := buildVerifiableMacaroon(t, budget, 25.00)
	if _, err := macaroon.Verify(encoded, policy, now); err != nil {
		t.Fatalf("at-cap should be allowed: %v", err)
	}
}
